### ISSUE TITLE
Trees don't grow on multiplayer

### ISSUE THREAD

**Issue by kociak1984** [Blu3wolf/Treefarm-AC#1]
When playing on singleplayer when I plant a germling it starts to grow.
On the contrary on multiplayer (dedicated server) those do not grow, they just stay on map as planted germlings. Also treefarm does not grow trees.
Funny enough the log says nothing.
As far we've tried Treefarm Lite 0.3.2 with Factorio 0.12.26.

**Comment by Blu3wolf** [comment]
Does this only happen when Treefarm-AC is installed?

**Comment by Blu3wolf** [comment]
Do treefarms plant trees, or not?

**Comment by kociak1984** [comment]
It mappens wether Treefarm-AC is installed or not. And no, treefarms don't plant any trees :(

**Comment by Blu3wolf** [comment]
Hmm. This issue should probably be opened in the treefarm-lite repository rather than this repo (treefarm-AC).

Can I get you to try it with version 0.3.3 of treefarm lite?

**Comment by kociak1984** [comment]
Sorry, my bad - too many opened tabs.
Version 0.3.3 seems to work fine on Factorio 0.12.26.
As I tried to replicate the situation I've found that this issue happens when mod has been added to an existing game (stop the server, add a mod, start the server). It does not happen when I start the game with "clean save", as in "./factorio --create blah && ./factorio --start-server blah".

**Comment by Blu3wolf** [comment]
Interesting. 0.3.2 is meant to work when added to an old game. I dont have access to a dedicated server to test with, though.

When you say 0.3.3 seems to work fine, do you mean that you cannot replicate the bug at all with 0.3.3? Or do you mean that it works fine, unless you add it to a game in progress?

**Comment by Blu3wolf** [comment]
Think I know how to fix this for the next version. Cheers!

0.3.2 does work fine, when you add it to an old game that originally had an old version of treefarm loaded. It does not work fine though, when you add it to an old game that never had any version of treefarm loaded!

**Comment by Blu3wolf** [comment]
check out https://github.com/Blu3wolf/Treefarm-Lite/releases for a new version, 0.3.4 - can you check to see if this fixes your issue?

If it does fix the issue, go ahead and close this one - and if it does fix the issue but also causes others, please open a new issue here: https://github.com/Blu3wolf/Treefarm-Lite/issues

Cheers! Hope that version works better for you!

**Comment by kociak1984** [comment]
OK, I just did a simple test: vanilla server, create save, start server, connect with vanilla client, wait for an autosave, exit, install the version you've mentioned, start server and client.
I confirm that the trees are growing now, so issue is to be closed.
Workaround for 0.3.3 and earlier: start game locally with TreeFarm-Lite, then copy save file to the server and start there.
