### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ThatCalvineGuy** [Blu3wolf/Treefarm-AC#2]
similar to when trying to run a mod which is out of date

**Comment by Blu3wolf** [comment]
Could I get some details? Version of Treefarm-AC used and all other mods installed, version of Factorio, the error message?

**Comment by shiv9** [comment]
I had the same problem.
Launched by changing the mod folder name.
"Treefarm-AC-0.2.3" to "Treefarm-AC_0.2.3"

**Comment by Blu3wolf** [comment]
Cheers for the feedback! Just so you know, you dont have to unzip mods for Factorio to recognise them - they will work just as well when still zipped, and will take up less space, too.
