### ISSUE TITLE
Cokery building not functioning after placement

### ISSUE THREAD

**Issue by csatlos** [Blu3wolf/Treefarm-AC#3]
After placing the Cokery building, it is not possible to actually use it. The attached screenshot shows the menu displayed when clicking on the building, but all options are red and non-selectable and hovering over the Charcoal item shows no "Made In" buildings (there is definitely power to the structure)

Game/Mod versions are:
- Factorio base 0.12.35
- HARDmod 0.1.0
- Treefarm-Lite 0.4.1
- Treefarm-AC 0.2.3
- Bob's Library 0.12.4
- Bob's Config 0.12.3 _disabled_
- Bob's Enemies 0.12.7 _disabled_
- Bob's Ores 0.12.7 _disabled_
- Bob's Modules 0.12.9 _disabled_
- Bob's Metals, Chemicals, and Intermediates 0.12.11 _disabled_
- Bob's Tech 0.12.4 _disabled_

![Building Popup Screenshot](https://cloud.githubusercontent.com/assets/6238508/16136446/75a09ef0-33f8-11e6-8bc0-a13191e7c638.jpg)

**Comment by Blu3wolf** [comment]
Note that with HARDmod installed, issues raised should be made on the HARDmod repo, not Treefarm. This is because HARDmod makes lots of changes to everything Treefarm related - in short HARDmod requires Treefarm, but Treefarm does not support HARDmod - if that makes sense.

**Comment by Blu3wolf** [comment]
This is likely the result of recent changes to Treefarm not being reflected in HARDmod. Will have to take a look at it. 

For future reference, you can report HARDmod issues here: https://github.com/Blu3wolf/HARDmod/issues

If the bug persists without HARDmod enabled, then it is correct to report it here. Cheers!

**Comment by Blu3wolf** [comment]
Found issue, bug in treefarm-replace.lua line 38
`data.raw["assembling-machine"]["tf-cokery"].crafting_categories = {"cokery-crafting"}`

That should be the correct line. Note the added curly brackets around "cokery-crafting".

**Comment by Blu3wolf** [comment]
Should be fixed in HARDmod 0.1.0 Alpha 5 (now released). If the issue persists, or you have other issues with HARDmod, please dont hesistate to report them here: https://github.com/Blu3wolf/HARDmod/issues

Cheers!
