### ISSUE TITLE
Crash on loading saved map with treefarm elements. Factorio 13.6 Treefarm 5.0.1 

### ISSUE THREAD

**Issue by Glendening** [Blu3wolf/Treefarm-AC#5]
I feel dumb for not posting this here.

Was playing using factorio 13.6 with bobs mods and tree farm. Everything was fine. Saved and quit. Came back later and tried to load the save and the following error pops up which prevents the save from being loaded.

Error while running mod-Treefarm-Lite::on_load().

Detected modifications to the 'global' table:
CRC before: 3901586395
CRC after: 179597676

Disabling the treefarm mod, loading the map. and letting it clear the treefarm objects allows the save to work.

Saving the now working map, enabling treefarm, loading the save works.

Trying to replicate the error now.

At least one other person reported the same issue on https://mods.factorio.com/mods/Blu3wolf/Treefarm-Lite/discussion/400

**Comment by Blu3wolf** [comment]
So yeah, this is just on Treefarm Lite, not Treefarm AC. Im going to close this one, and use the issue on the TF Lite repo.
