### ISSUE TITLE
Migration scripts cause errors

### ISSUE THREAD

**Issue by DarkHelmet433** [Blu3wolf/Treefarm-AC#6]
The Treefarm-AC/migrations/\* scripts all trigger an error in 0.13, using 0.3.0 prerelease 1.  

game.player no longer exists.  The scripts appear redundant and deleting them seems to work fine.

**Comment by Blu3wolf** [comment]
Thanks for the report. They have been removed for prerelease 2, but Ive been mostly working on treefarm lite so far. Ill see about getting Treefarm AC up soon.
